# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from engine.v1 import engine_pb2 as engine_dot_v1_dot_engine__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in engine/v1/engine_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class EngineWorkerStub(object):
    """Minimal EngineWorker API for a vLLM-like engine
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/engine.v1.EngineWorker/Health',
                request_serializer=engine_dot_v1_dot_engine__pb2.HealthRequest.SerializeToString,
                response_deserializer=engine_dot_v1_dot_engine__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.CreateSession = channel.unary_unary(
                '/engine.v1.EngineWorker/CreateSession',
                request_serializer=engine_dot_v1_dot_engine__pb2.CreateSessionRequest.SerializeToString,
                response_deserializer=engine_dot_v1_dot_engine__pb2.CreateSessionResponse.FromString,
                _registered_method=True)
        self.StartSequence = channel.unary_unary(
                '/engine.v1.EngineWorker/StartSequence',
                request_serializer=engine_dot_v1_dot_engine__pb2.StartSequenceRequest.SerializeToString,
                response_deserializer=engine_dot_v1_dot_engine__pb2.StartSequenceResponse.FromString,
                _registered_method=True)
        self.Prefill = channel.unary_unary(
                '/engine.v1.EngineWorker/Prefill',
                request_serializer=engine_dot_v1_dot_engine__pb2.PrefillRequest.SerializeToString,
                response_deserializer=engine_dot_v1_dot_engine__pb2.PrefillResponse.FromString,
                _registered_method=True)
        self.Decode = channel.unary_unary(
                '/engine.v1.EngineWorker/Decode',
                request_serializer=engine_dot_v1_dot_engine__pb2.DecodeRequest.SerializeToString,
                response_deserializer=engine_dot_v1_dot_engine__pb2.DecodeResponse.FromString,
                _registered_method=True)
        self.ReleaseSequence = channel.unary_unary(
                '/engine.v1.EngineWorker/ReleaseSequence',
                request_serializer=engine_dot_v1_dot_engine__pb2.ReleaseSequenceRequest.SerializeToString,
                response_deserializer=engine_dot_v1_dot_engine__pb2.ReleaseSequenceResponse.FromString,
                _registered_method=True)


class EngineWorkerServicer(object):
    """Minimal EngineWorker API for a vLLM-like engine
    """

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartSequence(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Prefill(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Decode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReleaseSequence(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EngineWorkerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=engine_dot_v1_dot_engine__pb2.HealthRequest.FromString,
                    response_serializer=engine_dot_v1_dot_engine__pb2.HealthResponse.SerializeToString,
            ),
            'CreateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSession,
                    request_deserializer=engine_dot_v1_dot_engine__pb2.CreateSessionRequest.FromString,
                    response_serializer=engine_dot_v1_dot_engine__pb2.CreateSessionResponse.SerializeToString,
            ),
            'StartSequence': grpc.unary_unary_rpc_method_handler(
                    servicer.StartSequence,
                    request_deserializer=engine_dot_v1_dot_engine__pb2.StartSequenceRequest.FromString,
                    response_serializer=engine_dot_v1_dot_engine__pb2.StartSequenceResponse.SerializeToString,
            ),
            'Prefill': grpc.unary_unary_rpc_method_handler(
                    servicer.Prefill,
                    request_deserializer=engine_dot_v1_dot_engine__pb2.PrefillRequest.FromString,
                    response_serializer=engine_dot_v1_dot_engine__pb2.PrefillResponse.SerializeToString,
            ),
            'Decode': grpc.unary_unary_rpc_method_handler(
                    servicer.Decode,
                    request_deserializer=engine_dot_v1_dot_engine__pb2.DecodeRequest.FromString,
                    response_serializer=engine_dot_v1_dot_engine__pb2.DecodeResponse.SerializeToString,
            ),
            'ReleaseSequence': grpc.unary_unary_rpc_method_handler(
                    servicer.ReleaseSequence,
                    request_deserializer=engine_dot_v1_dot_engine__pb2.ReleaseSequenceRequest.FromString,
                    response_serializer=engine_dot_v1_dot_engine__pb2.ReleaseSequenceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'engine.v1.EngineWorker', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('engine.v1.EngineWorker', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EngineWorker(object):
    """Minimal EngineWorker API for a vLLM-like engine
    """

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engine.v1.EngineWorker/Health',
            engine_dot_v1_dot_engine__pb2.HealthRequest.SerializeToString,
            engine_dot_v1_dot_engine__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engine.v1.EngineWorker/CreateSession',
            engine_dot_v1_dot_engine__pb2.CreateSessionRequest.SerializeToString,
            engine_dot_v1_dot_engine__pb2.CreateSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartSequence(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engine.v1.EngineWorker/StartSequence',
            engine_dot_v1_dot_engine__pb2.StartSequenceRequest.SerializeToString,
            engine_dot_v1_dot_engine__pb2.StartSequenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Prefill(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engine.v1.EngineWorker/Prefill',
            engine_dot_v1_dot_engine__pb2.PrefillRequest.SerializeToString,
            engine_dot_v1_dot_engine__pb2.PrefillResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Decode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engine.v1.EngineWorker/Decode',
            engine_dot_v1_dot_engine__pb2.DecodeRequest.SerializeToString,
            engine_dot_v1_dot_engine__pb2.DecodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReleaseSequence(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engine.v1.EngineWorker/ReleaseSequence',
            engine_dot_v1_dot_engine__pb2.ReleaseSequenceRequest.SerializeToString,
            engine_dot_v1_dot_engine__pb2.ReleaseSequenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
